### ISSUE TITLE
GitOps Improvements

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/moondog-engine#40]
During my interview with @grossvogel on Friday, he brought up an area of concern / improvement: how GitOps plays into the use of MDE.

Here are my notes, but I'll lean on @grossvogel to clean them up a bit and make better sense of them:

- GitOps concerns
    - You can't check in the apps/operators to Git
    - You can't update the versions via MDE
    - You can't commit updates via Git to make updates
    - This feels weird ^^

## To Do
- Explore this theme
- If we want to pursue this theme, ideate a few solutions
- Decide what solution(s) to pursue
- Split out into workable Issue(s)

**Comment by bit-herder** [comment]
I agree with jason here... we tried to do everything via gitops for the spacewalk cluster and were unable to for various reasons.

**Comment by grossvogel** [comment]
I think a lot of the pain I feel is that I'm used to managing _apps_ inside a running cluster, which means working with plain old Kubernetes resources... plus secrets, which are already a pain point but there are ways to deal with them, like SealedSecrets.

Moondog Engine mostly works with helm charts, and it seems that many / most of them weren't designed for gitops. They often expose configuration as plain text or base64-encoded strings, and those can't be in git if they're sensitive.

The only idea I have so far about how to get around that is to create our own helm chart that consumes secret keys via Secret resource references and passes those values on to the underlying helm chart.

**Comment by vaxinate** [comment]
I don't really think we should "work around" this problem. When we encounter charts that we want to make a part of moondog engine that require us to put plaintext secrets in the values, we should be modifying those charts so that we can provide the same configuration via an existing secret and making PRs to the chart's main repo. I've been doing this. Some chart owners are slower than others to accept the pull requests, but the [helm operator](https://github.com/fluxcd/helm-operator) makes it easy to use a forked version from github in the meantime.

**Comment by vaxinate** [comment]
I'll concede that may not be realistic since harbor and prometheus operator are both guilty of this and forcing them into compliance might be more complicated since those are bigger projects with complex helm charts, but the idea of implementing a work around for this problem gives me the heebie jeebies. I'd almost just rather leave it all out of gitops.

**Comment by grossvogel** [comment]
Yeah, I guess part of the intro to my comment was along the lines of, "Maybe people with more experience managing these things don't typically feel it's important to have _all of the things_ in git." I think it's a decision of project values and priorities

**Comment by vaxinate** [comment]
I do think that ultimately we want as much cluster config as possible to be manageable via gitops, so this is a good topic to explore. I'm definitely not advocating for forgetting about it. I just would be sad if we saddled ourselves with building/maintaining a rube goldberg machine for fixing bad charts. I'd rather just fix the bad charts since they're all open source and I expect few chart maintainers will refuse PRs that improve their chart's usability. 

Until we have time/motivation to do that, I think we could either punt entirely, or selectively put helm releases in gitops that don't have secrets in them. I think I'm inclined toward being consistent.

**Comment by grossvogel** [comment]
Inventory of sensitive info in MDE output, so we can take stock of where we are and what we're up against:
- :white_check_mark: **aws-ebs**
- :white_check_mark: **cert-manager**
- :red_circle: **dex** has lots of oauth client secrets in the chart values
- :warning: **flux** has git creds in a secret, which theoretically could be sealed
- :red_circle: **gangway** has oauth client secret and sessionKey in the chart values
- :warning: **harbor-kubedb** has AWS and DB creds in a secret, which theoretically could be sealed
- :red_circle: **harbor** has admin password, secret key, db credentials, and AWS keys in the chart values
- :white_check_mark: **kubedb**
- :white_check_mark: **loki-stack**
- :white_check_mark: **nginx-ingress**
- :red_circle: **oauth2-proxy** has client secret and cookie secret in the chart values
- :red_circle: **prometheus-operator** has an oauth client cert and admin PW for grafana in the chart values and a private key for the etcd healthcheck client in a secret
- :white_check_mark: **sealed-secrets**
- :white_check_mark: **user-permissions**
- :warning: **velero** has AWS creds in a secret, which theoretically could be sealed
- :red_circle: **navigator** has an oauth client secret in the chart values

**Comment by jwietelmann** [comment]
This should help: https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/values/#values-from-sources

**Comment by grossvogel** [comment]
Oh, wow! That solves pretty much the whole issue, except figuring out how to _seal_ secrets as a part of the install process.

**Comment by jwietelmann** [comment]
Rough sketch of an idea:

1. Isolate all secret bits into `Secret`s that are referenced by the relevant `HelmRelease`s.
2. Update our template directory file scheme to put k8 resources in their own files with naming conventions we can use to identify their type. E.g., `foo.secret.yaml`, `foo.namespace.yaml`, `foo.helmrelease.yaml`.
3. (Optionally?) `kubeseal` every `*.secret.yaml` file.

**Comment by jwietelmann** [comment]
started work here: https://github.com/revelrylabs/moondog-engine/pull/52/files

**Comment by jwietelmann** [comment]
Secrets now get sealed as part of the install process. Is there anything else to do here?

**Comment by grossvogel** [comment]
It _might_ make sense to mention something about this in the readme, both in as an instructional point and a value proposition.

We maybe also ought to test that everything works as expected if you check this output into the flux branch?

**Comment by bit-herder** [comment]
this does work now. Closing
