### ISSUE TITLE
Test install from a non-Terraform test cluster

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/moondog-engine#41]
## Background
We discussed testing MDE on a vanilla flavored k8s cluster that was NOT instantiated by our-terraform 
- to find bugs/make sure it works
- to find things to document

## A/C
- [ ] I stand up a non-tf cluster in aws
- [ ] I run the installer
- [ ] the installer completes AND
- [ ] the system works as intended 

Output of this ticket should be small fixes and docs, if larger changes are required we should open up a ticket for each of them - see #39 .

**Comment by iamjoshfrank** [comment]
Some comment history via https://github.com/revelrylabs/cluster-ops/issues/1155

> @bit-herder 
> leaning towards kubespray for this
> 
> https://www.altoros.com/blog/installing-kubernetes-with-kubespray-on-aws/

> @vaxinate 
> oh yeah this would be a cool opportunity to take kubespray for a ride

**Comment by bit-herder** [comment]
@grossvogel  im going to knock out whats in cluster-ops implement then switch over here probably, ill hit you up when I do. If you get to it first, thats cool too.

**Comment by grossvogel** [comment]
@bit-herder and I spent some time on this today. We decided to try getting a fresh cluster set up in AWS using Kubespray because some of us have been curious about the tool. We followed [these instructions](https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/terraform/aws/README.md), and this is a sketch of our 

- Kubespray is basically a bunch of Ansible config, so you need your instances and network setup already to use Kubespray
- There's an AWS Terraform setup in their contrib folder to get you there and spit out the necessary "inventory" file, which is a list of hosts and their roles so that Ansible knows what to do on each host
- Terraform also sets up a bastion host (or 2?). When you run Ansible, it's supposed to generate an SSH config that lets it (or a human user) hop to each of the other hosts through the bastion. (It saves the config in a file so you can use it later, but it doesn't generate it 'til it has successfully connected.)
- So you run the Ansible command (`ansible-playbook -i ./inventory/hosts ./cluster.yml -e ansible_user=ubuntu -b --become-user=root --flush-cache`) and it's supposed to connect and do the right things on each host. (We were using `-e ansible_user=core` until later when we switched OS.)
- We had an issue with getting the right SSH key file to be used by Ansible, but eventually got it by manually adding `ansible_ssh_private_key_file=/path/to/private_key.pem` in in a new `[all:vars]` section of the inventory file. (The key is created or added to AWS as a part of the prep, so all you have to do on the Terraform side is tell it the _name_ of the key, but the Ansible side needs to find the key too and it doesn't AWS.)
- We finally connected and discovered there's no python (required by Ansible) on the bastion b/c they default to CoreOS
- SSH'd into the bastion to install python but CoreOS doesn't allow installing. Found a sketchy script to do it but then ran out of disk space.
- Started over with ubuntu instances. Took us a couple of tries b/c we used the ami id setting from the `terraform.tfvars.example` file the first time around. The way recommended in the README (editing `variables.tf`) did work, so we destroyed and rebuilt the cluster with that.
- Fresh cluster, re-applied the ssh key file setting to the inventory file, and things went forward. It took a good half-hour and logging was pretty verbose, showing each thing it did on each host.
- We think we got a cluster but it appears we have to SSH into the masters to get config info. There's an option to have Ansible spit out the kubeconfig file locally but we didn't set it: https://github.com/kubernetes-sigs/kubespray/blob/master/docs/getting-started.md#accessing-kubernetes-api

Tomorrow we get our kubeconfig sorted out, verify that the cluster is healthy, and start building out a moondog config for it by hand.

**Comment by grossvogel** [comment]
I've spent some time today on the thought exercise of "what would it be like to make a `config/values.yaml` file from scratch," focusing more on how one would know what things to put where than how to get or create the things.

The current instructions say to use a copy of the existing `values.yaml` file as a starting point, but my impression is that there's a tension between that file being both the home for the defaults and also a starting point for custom config. The file is mostly filled with things you don't need or want to change, and many of the things you really need to supply are left out b/c they're not default-able.

I'm kind of assuming that a first-time user want to supply only the required configuration and accept the (very sensible) defaults. Possibly after digging in they'd want to tweak a couple of things they care about, but nobody gets off the ground w/o the _required_ stuff. I found myself largely at a loss w/o going back to previously generated `values.yaml` files to figure out what's really required and where it fits. (I should have had more discipline and used the docs.)

Anyway, my knee-jerk reaction is that it might be better to have one file for defaults and another example file to show what you need to fill in to install successfully. If you want to add tweaks on top of that, the docs are good. (The docs are decent at telling you about the required settings, too, but it's kind of a cross-referencing rodeo to collate the info and get the yaml paths nested properly.)

The same problem might also be solved by large stanzas of commented out config, which I think works great for the [auth section](https://github.com/revelrylabs/moondog-engine/blob/baca3a076f0db49dd70e42114900c927f439c3aa/values.yaml#L83-L102) but might not work so well when there's a significant amount of both default and user-supplied info in the same section, interleaved through the hierarchy. (There's also a small gotcha waiting there for somebody who uncomments the code but doesn't remove the `[]` from the top line.)

**Comment by bit-herder** [comment]
OK so i finally have some updates here after fighting with kubespray for awhile... we used their contrib terraform, which was our first mistake. It wasn't very good and it spit out files in a weird spot. We also followed the `readme` from that folder and it turned out to have some important bits but not be very complete. 

After going thru `getting started` more general instructions we got much further. 

Turns out there were a few key things we were missing

- you need to COPY the local/sample inventory to ANOTHER folder 'mycluster' for things to work quite right
- you need to copy the generated inventory (which LOOKS like its in the right place for ansible) into that directory and then specify those things in your playbook run 
- if you go playing with the vars files (of which there are quite a few, kubespray has a TON of options) be sure you are using arguments that things will accept, since there don't seem to be any guards around at least some of them, like etcd's volume size and memory limits. 
- ansible playbooks can check for things like that in weird ways and not expose the underlying problem, just some symptom. For instance, my etcd change was an incorrectly formatted argument and it prevented etcd from starting, but ansible just reported a non-functional etcd so I had to dig
- ansible doesn't really have a plan/apply thing like terraform does. Its more change and pray. There is a dry-run thing but its not useful
- ansible has verbose but fairly useless output

IN ANY CASE, we now have a working cluster that should be set up for MDE so I will begin testing that. I sort of got sidetracked by kubespray, but we wanted to test it as a possible candidate for taking over kubernetes management from our current bash scripts, but so far it seems a little complex and a bit scary to run. 

I am now going to attempt to get the current MDE to install on it.

**Comment by bit-herder** [comment]
re: @grossvogel comment -ive seen this solved mostly in helm charts by large stanzas of commented out config. It seems easier that wrestling with multiple files to me.  See something like the prometheus-operator chart values file here

https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml

**Comment by grossvogel** [comment]
@bit-herder got the kubespray cluster humming yesterday so we got a chance to install (and uninstall and install again) and I think we can conclude that technically it was a success.

### Building the config
- We again started from an existing generated `values.yaml` rather than piecing things together from the defaults and documentation.
- The first challenge was getting the PKI files from the masters. Chris used rsync over ssh along with kubespray's bastion config and `--rsync-path="sudo rsync"` to copy those directly from the masters. A tough ask for me, but apparently not for a seasoned sysadmin.
- The healthcheck-client certs for etcd were nowhere to be found, though. For testing, we grabbed some existing client certs but in real life I think you'd have to generate a pair key and sign the cert with etcd's CA.
- While filling out the values, we noticed that _a lot_ of the things you have to supply are just random strings. In some cases MDE can generate these for you if you want, but in other cases it can't (right now) because it needs to use _the same_ random secret in multiple disparate template files. It'd be nice if we could do what terraform does and generate random _but stable_ secrets w/o forcing the user to supply them.

### Installation
- We installed the first time using `letsencrypt-staging` so we could iterate to iron out any kinks w/o getting banned. Kinks weren't very prevalent. We had gotten the AWS region wrong in our velero config, but everything else seemed healthy.
- We uninstalled and re-installed with "real" TLS certs. Wran into #53 but things proceeded normally after manually deleting that CRD.
- OAuth flows now worked fine, which let us get into prometheus to see about the etcd healthcheck situation. Two things looked not quite right in prometheus:
    - First, are no etcd targets listed. I believe this is because our cluster's etcd installation is not in the cluster. The prometheus chart accepts a value in `kubeEtcd.endpoints` for this use case, which I attempted to fill with the IPs of the etcd servers, but the HelmRelease deployment failed. I may be using the wrong format or perhaps there are other settings required to operate in this mode. We also haven't verified whether the etcd nodes are listening on the default metrics port of 4001.
    - There are targets listed for `kube-proxy` but they're all showing connection errors when prom tries to scrape them. Looking at the `kube-proxy` configuration makes me think it's because the metrics endpoint is configured on loopback (127.0.0.1) instead of on 0.0.0.0. I've been hesitant to try this b/c I know `kube-proxy` is important to the functioning of the cluster. (@bit-herder maybe you want to give this a try with me?)
- Another thing we noticed is that we're seeing lots of evicted pods. Our test cluster is perhaps not quite beefy enough to host all of MDE, and it would probably be a good idea to have guidelines on the kinds of resources required for a stable installation.

The monitoring issues seem like the kinds of things that are going to be highly variable based on the k8s installation and I would expect many / most cluster admins need to tweak a few things to get monitoring up to 100%. It probably makes sense for us to make the etcd monitoring a bit more configurable, though?

**Comment by bit-herder** [comment]
i think you are right about etcd. I found this post

https://jpweber.io/blog/monitoring-external-etcd-cluster-with-prometheus-operator/

etcd is indeed external here, running as a service on its own set of nodes. I think if we follow that we should get etcd going. 

And I completely missed kube-proxy.. thanks.. ill have a look at that as well. It would be cool to list at least one large k8s installer as "supported" or whatever.

**Comment by bit-herder** [comment]
Jason's fix (editing the configmap so that kube-proxy listens on all interfaces `0.0.0.0` instead of just loopback `127.0.0.1` seems to have gotten that bit working. I'm going to try to go thru this blog post to get etcd monitoring working and then we should be good.

**Comment by grossvogel** [comment]
@bit-herder got the etcd monitoring solved by adjusting the `Service` and `Endpoints` for prom's etcd monitoring service. It might be nice to figure out if we can achieve those adjustments through Moondog Engine configuration and the helm chart, though?

**Comment by bit-herder** [comment]
yeah it might be a good idea to do that.  I think that the changes I made  would work for any cluster with external etcd, assuming you can grab the certs for etcd.

**Comment by bit-herder** [comment]
ok, this is done. I think we can safely say that MDE works on a kubespray-installed cluster with some small adjustments. It also gives us fodder for more tickets/ideas. 

This gives us evidence that MDE will work on most vanilla k8s distros running in AWS without much modification. We may want to document the exact steps in the readme. 

But generally, this is really good news
