### ISSUE TITLE
Current ClusterRoles are a little misleading and/or nonsensical

### ISSUE THREAD

**Issue by jwietelmann** [revelrylabs/moondog-engine#5]
The admin one makes sense, but the other "readonly" one has some weird issues:

* Can delete pods
* Can't `get` secrets
* But can `list` secrets
* And can `watch` secrets

**Comment by vaxinate** [comment]
being allowed to `watch` is probably a mistake.

**Comment by vaxinate** [comment]
Yeah. "readonly" is not a particularly clear name. Some of the extra stuff is good: We're allowing users to delete pods so they can restart their own applications. Some of it is less good: I didn't realize at first the listing secrets meant that you could see the contents of the listed secrets, and having `watch` on the list is probably just straight up a mistake

We don't want plain users to be able to see the contents of secrets though without having their privileges specifically escalated. However, turning off `list` means plain users can't even see what secrets exist :-/

**Comment by jwietelmann** [comment]
Unfortunately there's no way in Kubernetes to let users `list` secrets without allowing them to read the contents, so I'm inclined to redo this and revoke that. I think we should chop up these roles and allow some more configuration.

There should be several ClusterRoles, and you should be able to bind your groups multiple of them:

* read/write all
* read all except secrets
* read secrets
* delete pods
* create secrets?
* create namespaces?

**Comment by vaxinate** [comment]
Yeah that seems mostly right. "Read secrets" will probably be more complicated since I doubt we'll want to ever give a single user that's not got full read/write to have blanket read/write privileges on secrets. I kind of expected at some point we'd make namespace bound Roles (vs cluster-wide ClusterRoles) to provide permissions for secrets on indvidual namespaces. At the same time, every time I think about how we'd actually execute on that concept in a practical way my brain gets a little melty, and I can't make any conclusions about whether or not it even really matters.

**Comment by jwietelmann** [comment]
done
